# Generated by Django 4.2.3 on 2023-09-12 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgPath', models.CharField(max_length=400, verbose_name='图片地址')),
                ('describes', models.CharField(max_length=100, verbose_name='图片描述')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'carousel_t',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=20, verbose_name='类别名字')),
            ],
            options={
                'verbose_name_plural': '商品类别',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_name', models.CharField(max_length=100, verbose_name='商品名字')),
                ('price', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='商品价格')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='商品销售价格')),
                ('img', models.CharField(max_length=200, verbose_name='商品默认图片')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='商品标题')),
                ('instruction', models.TextField(verbose_name='商品的描述信息')),
                ('count', models.IntegerField(default=0, verbose_name='商品销售数量')),
                ('stock', models.IntegerField(default=0, verbose_name='商品库存数量')),
                ('online', models.BooleanField(default=True, verbose_name='是否在售')),
            ],
            options={
                'verbose_name_plural': '商品信息',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200, verbose_name='图片')),
                ('title', models.CharField(max_length=20, null=True, verbose_name='图片的描述')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品所属图片')),
            ],
            options={
                'db_table': 'goodimg',
            },
        ),
        migrations.CreateModel(
            name='GoodsCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品收藏',
                'verbose_name_plural': '商品收藏',
                'db_table': 'goods_collect',
            },
        ),
    ]
