# Generated by Django 4.2.3 on 2023-09-12 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='订单号')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='总价')),
                ('freight', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='运费')),
                ('total_count', models.IntegerField(default=1, verbose_name='商品总数')),
                ('pay_method', models.CharField(choices=[(1, '支付宝'), (2, '银联')], max_length=10, verbose_name='支付方式')),
                ('pay_status', models.CharField(choices=[(0, '待支付'), (1, '待发货'), (2, '待收货'), (3, '待评价'), (4, '已完成')], default=0, max_length=10, verbose_name='支付状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
                'db_table': 'tb_order',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='单价')),
                ('comment', models.TextField(default='', verbose_name='评价信息')),
                ('score', models.SmallIntegerField(choices=[(0, '0分'), (1, '20分'), (2, '40分'), (3, '60分'), (4, '80分'), (5, '100分')], default=5, verbose_name='满意度评分')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='是否匿名评价')),
                ('is_commented', models.BooleanField(default=False, verbose_name='是否评价')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='订单商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderGood', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单商品表',
                'verbose_name_plural': '订单商品表',
                'db_table': 'order_goods_table',
            },
        ),
    ]
